version: '3.8'
services:
  app:
    build: ./dockerfiles
    depends_on:
      - db
    image: jackmarket
    container_name: jackmarket-backend-app
    restart: always
    volumes:
      - ./:/var/www
      - "./dockerfiles/config/php/php-fpm.conf:/etc/php-fpm.conf"
      - "./dockerfiles/config/php/www.conf:/etc/php-fpm.d/www.conf"
      - "./dockerfiles/config/php/php.ini:/usr/local/etc/php/php.ini"
      - "./dockerfiles/config/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini"
    environment:
      DB_DATABASE: '${DB_DATABASE}'
      DB_USERNAME: '${DB_USERNAME}'
      DB_PASSWORD: '${DB_PASSWORD}'
      DB_HOST: '${DB_HOST}'
      DB_PORT: '${DB_PORT}'
    networks:
      - jackmarket

  db:
    image: mysql:8.0
    container_name: jackmarket-db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - jeckmarket-db:/var/lib/mysql
    networks:
      - jackmarket

  nginx:
    image: nginx:alpine
    container_name: jackmarket-nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - "./dockerfiles/config/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - jackmarket

networks:
  jackmarket:
    driver: bridge

volumes:
  jeckmarket-db: